import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import { Provider } from "jotai";

// 使用本地 Roboto 可变字体
const roboto = localFont({
  src: "../fonts/Roboto-VariableFont_wdth,wght.ttf",
  weight: "100 900",
  style: "normal",
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <TRPCReactProvider>
        <NuqsAdapter>
          <Provider>
          {children}
          </Provider>
        </NuqsAdapter>
        <Toaster/>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
